// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv

import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // If you use a transaction pooler (Supabase/Neon),
    // use the DIRECT_URL here so migrations work correctly.
    // Otherwise, use DATABASE_URL.
    url: process.env.DIRECT_URL ?? env("DATABASE_URL"),
  },
});
